[workspace]
resolver = "2"
members = [
    "alg",
    "tools",
    "examples/*"
]

[workspace.dependencies]
alg = { path = "alg" }
tools = { path = "tools" }
ndarray = "*"

[profile.dev]
opt-level = 3
