[workspace]
resolver = "2"
members = ["alg", "tools", "examples/*"]

[workspace.dependencies]
alg = { path = "alg" }
tools = { path = "tools" }
ndarray = "*"
egui = { version = "0.31.0" }
eframe = { version = "0.31.0" }
egui_extras = { version = "0.31.0", features = ["all_loaders"] }
egui_plot = { version = "0.31.0" }
md-5 = "*"
hex = "*"
layout-rs = "*"
anyhow = "*"
tracing = "*"
tracing-subscriber = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
regex = "*"

# [profile.dev.package."*"]
# opt-level = 3

[patch.crates-io]
egui = { git = "https://github.com/passchaos/egui.git", branch = "feat/0.31-svg-text" }
egui_extras = { git = "https://github.com/passchaos/egui.git", branch = "feat/0.31-svg-text" }

# egui = { path = "../egui/crates/egui" }
# egui_extras = { path = "../egui/crates/egui_extras" }
