[package]
name = "classify_person"
version = "0.1.0"
edition = "2024"

[dependencies]
alg = { workspace = true }
tools = { workspace = true }
ndarray = { workspace = true }
tracing = "*"
tracing-subscriber = "*"
