[package]
name = "alg"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tracing-subscriber = "0.3.19"
tools = { workspace = true }
