[package]
name = "nlp_learn"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }
alg = { workspace = true }
openblas-src = { workspace = true }
